### ISSUE TITLE
Define object-relational mapping

### ISSUE THREAD

**Issue by lplade** [lplade/itec2905_project4#5]
We'll use the Flask-SQLAlchemy module to simplify interface between Flask and SQL server.

I'm thinking we'll just start out using SQLite as a backend?

**Comment by lplade** [comment]
Not strictly a project requirement. See issue #7. Closing for now, will re-open if actually needed.

**Comment by BorisVV** [comment]
Larry I need you to send me an invitation because it won't let push my code.
