### ISSUE TITLE
Design database structure

### ISSUE THREAD

**Issue by lplade** [lplade/itec2905_project4#6]
We need to figure out which data we need to store and design tables for it. ORM means we should not need to write any actual SQL code.

One thing the database must support is the ability to cache any data retrieved from an API for, say, 30 minutes, so it can supply this data instead of repeating API calls.

**Comment by lplade** [comment]
Will SQLite be sufficient?

**Comment by BorisVV** [comment]
As discussed today in class, will see. But SQLite is definitely a good choice.

**Comment by lplade** [comment]
I will close this for now. If we are lucky we can avoid DB. Will re-open if we have to use it.
